# Generated by Django 4.2.6 on 2023-10-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applicant_user_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='score',
        ),
    ]
