# Generated by Django 4.2.6 on 2023-10-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_application_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
